Spacy on subdocument
GateNLP/python-gatenlp pull request #128
Opened 2021-09-07 19:10 UTC by joancf

Changes in lib_spacy
A new parameter "start_offset" has been added to spacy2gatenlp. This allows to annotate pats on an existing document not starting at position zero.  

A new function `apply_spacy2ann` allows to annotate parts of a document using a given spacy pipeline. This allows to apply different  pipelines to different parts of a document (for any reason: different language, different format...)

2021-09-07 19:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GateNLP/python-gatenlp?pullRequest=128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GateNLP/python-gatenlp?pullRequest=128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GateNLP/python-gatenlp?pullRequest=128) it.</sub>

2021-09-08 07:38 UTC, johann-petrak requested changes
Looks good, thank you! However  I think it would actually be better to merge the functionality of apply_spacy2ann into the existing apply_spacy method by adding a kwarg containing_anns=None. If containing_anns is None, processing is done for the whole document as before, otherwise it is assumed to be either an annotation set in which case we iterate over the anns as you do using  fast_iter or some other iterable in which case we just iterate over it directly. 
I think that would simplify the API and make the processing over containing anns more flexible.

2021-09-08 18:27 UTC, joancf commented
Done!

2021-09-08 19:54 UTC, johann-petrak commented
Thanks! 
To speed this up I will merge and slightly update the code afterwards.

2021-09-08 19:55 UTC, merged